.PHONY: all clean

all:
	@(cd agents; make)
	@(cd init; make)
	@(cd uninit; make)
	@(cd deploy; make)
	@(cd exec; make)
	@(cd run; make)

clean:
	@(cd agents; make clean)
	@(cd init; make clean)
	@(cd uninit; make clean)
	@(cd deploy; make clean)
	@(cd exec; make clean)
	@(cd run; make clean)


