/*
 * Copyright (c) 2020 Bitdefender
 * SPDX-License-Identifier: Apache-2.0
 */
///
/// @file       introstatus.h
/// @ingroup    group_public_headers
/// @brief      Status values returned by most functions that can signal different success or failure states.
///
/// This follows the NTSTATUS data type, and some values overlap those of known NTSTATUS values.
///

#ifndef _INTROSTATUS_H_
#define _INTROSTATUS_H_

///
/// @brief  The status data type.
///
/// This is organized in the same way NTSTATUS is organized:
/// @code
/// || Severity:2 | Customer: | Reserved | Facility | Code ||
/// @endcode
///
typedef _Return_type_success_(return >= 0) int INTSTATUS;

#define INT_MAKE_STATUS(severity, facility, code)       \
    (INTSTATUS)(0ULL +                                  \
                ((((severity) + 0ull)   << 30ULL)       \
                 | ((1 + 0ull)          << 29ULL)       \
                 | (((facility) + 0ull) << 16ULL)       \
                 | (((code) + 0ull))))


//
// Severity-related definitions
//
#define INT_STATUS_SEVERITY_SUCCESS         0x0ULL
#define INT_STATUS_SEVERITY_INFORMATIONAL   0x1ULL
#define INT_STATUS_SEVERITY_WARNING         0x2ULL
#define INT_STATUS_SEVERITY_ERROR           0x3ULL

#define INT_SUCCESS(Status)                 (__likely(((int)(Status)) >= 0))

// Common statuses
#define INT_FACILITY_COMMON                 0x100

// hvi
#define INT_FACILITY_HVI                    0x240
#define INT_FACILITY_HVI_MAXIMUM_VALUE      0x25F   // 0x20 (32) 'components'

//
// Success value(s)
//
#define INT_STATUS_SUCCESS                       ((INTSTATUS)0)

//
// parameter validation errors
//
#define INT_STATUS_INVALID_PARAMETER \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x00)

#define INT_STATUS_INVALID_PARAMETER_1 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x01)

#define INT_STATUS_INVALID_PARAMETER_2 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x02)

#define INT_STATUS_INVALID_PARAMETER_3 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x03)

#define INT_STATUS_INVALID_PARAMETER_4 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x04)

#define INT_STATUS_INVALID_PARAMETER_5 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x05)
    
#define INT_STATUS_INVALID_PARAMETER_6 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x06)

#define INT_STATUS_INVALID_PARAMETER_7 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x07)

#define INT_STATUS_INVALID_PARAMETER_8 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x08)

#define INT_STATUS_INVALID_PARAMETER_9 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x09)

#define INT_STATUS_INVALID_PARAMETER_10 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0A)

#define INT_STATUS_INVALID_PARAMETER_11 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0B)

#define INT_STATUS_INVALID_PARAMETER_12 \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0C)

#define INT_STATUS_INVALID_PARAMETER_MIX \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0D)

//
// module/subsystem errors
//
#define INT_STATUS_COMPONENT_NOT_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x00 + 0x100)

#define INT_STATUS_COMPONENT_ALREADY_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x01 + 0x100)

#define INT_STATUS_COMPONENT_NOT_READY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x02 + 0x100)

#define INT_STATUS_COMPONENT_NOT_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x03 + 0x100)

#define INT_STATUS_COMPONENT_LIFECYCLE_ENDED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x04 + 0x100)

#define INT_STATUS_INVALID_COMPONENT_STATE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x05 + 0x100)

#define INT_STATUS_OPERATION_NOT_SUPPORTED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x06 + 0x100)

#define INT_STATUS_OPERATION_NOT_IMPLEMENTED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x07 + 0x100)

#define INT_STATUS_INVALID_OPERATION_STATE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x08 + 0x100)

#define INT_STATUS_COMPONENT_BUSY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x09 + 0x100)


// data/buffer errors
#define INT_STATUS_INVALID_DATA_VALUE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x00 + 0x200)

#define INT_STATUS_INVALID_DATA_TYPE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x01 + 0x200)

#define INT_STATUS_INVALID_DATA_SIZE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x02 + 0x200)

#define INT_STATUS_INVALID_OBJECT_TYPE \
    INT_STATUS_INVALID_DATA_TYPE


// valid and supported most likely but some kind of redundant information is available and that info is contradictory
#define INT_STATUS_INCONSISTENT_DATA_VALUE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x03 + 0x200)

#define INT_STATUS_INCONSISTENT_DATA_SIZE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x04 + 0x200)

#define INT_STATUS_CORRUPTED_DATA \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x05 + 0x200)

#define INT_STATUS_DATA_NOT_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x06 + 0x200)

#define INT_STATUS_DATA_IN_USE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x07 + 0x200)

#define INT_STATUS_DATA_ALREADY_EXISTS \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x08 + 0x200)

#define INT_STATUS_DATA_ALREADY_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x09 + 0x200)
    
#define INT_STATUS_DATA_ALREADY_FREE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0A + 0x200)

#define INT_STATUS_DATA_NOT_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0B + 0x200)

#define INT_STATUS_DATA_NOT_READY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0C + 0x200)

#define INT_STATUS_DATA_LIFECYCLE_ENDED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0D + 0x200)

#define INT_STATUS_INVALID_DATA_STATE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0E + 0x200)

#define INT_STATUS_DATA_DOMAIN_OVERFLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0F + 0x200)

#define INT_STATUS_ALIGNMENT_INCONSISTENCY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x10 + 0x200)


// array or raw data handling
#define INT_STATUS_DATA_BUFFER_TOO_SMALL \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x11 + 0x200)

#define INT_STATUS_BUFFER_UNDERFLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x12 + 0x200)

#define INT_STATUS_BUFFER_OVERFLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x13 + 0x200)

#define INT_STATUS_OUT_OF_RESOURCES \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x14 + 0x200)

#define INT_STATUS_OUT_OF_MEMORY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x15 + 0x200)

#define INT_STATUS_INDEX_OUT_OF_RANGE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x16 + 0x200)

#define INT_STATUS_NO_MORE_ENTRIES \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x17 + 0x200)


// integer-arithmetic issues
#define INT_STATUS_ARITHMETIC_UNDERFLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x18 + 0x200)

#define INT_STATUS_ARITHMETIC_OVERFLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x19 + 0x200)


// valid, but not supported / can't be handled
#define INT_STATUS_UNSUPPORTED_DATA_VALUE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1A + 0x200)

#define INT_STATUS_UNSUPPORTED_DATA_TYPE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1B + 0x200)

#define INT_STATUS_UNSUPPORTED_DATA_SIZE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1C + 0x200)

#define INT_STATUS_DATA_OUT_OF_RANGE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1D + 0x200)


// key-value data structure statuses
#define INT_STATUS_KEY_ALREADY_EXISTS \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1E + 0x200)

#define INT_STATUS_KEY_NOT_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x1F + 0x200)


// synchronization and timing errors
#define INT_STATUS_ABORTED_ON_TIMEOUT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x01 + 0x400)

#define INT_STATUS_ABORTED_ON_CRITICAL_FAULT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x02 + 0x400)

#define INT_STATUS_DATA_ALTERED_FROM_OUSIDE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x03 + 0x400)

#define INT_STATUS_SYNCHRONIZATION_INCONSISTENCY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x04 + 0x400)


//
// generic status values
//
#define INT_STATUS_ALREADY_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x00  + 0x500)

#define INT_STATUS_NOT_INITIALIZED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x01  + 0x500)

#define INT_STATUS_UNEXPECTED_RACE_CONDITION \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x02  + 0x500)

#define INT_STATUS_INVALID_INTERNAL_STATE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x03  + 0x500)

#define INT_STATUS_OUT_OF_RANGE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x04  + 0x500)

#define INT_STATUS_UNINITIALIZED_STATUS_VALUE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x05  + 0x500)

#define INT_STATUS_INSUFFICIENT_RESOURCES \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x06  + 0x500)

#define INT_STATUS_NOT_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x07  + 0x500)

#define INT_STATUS_NOT_SUPPORTED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x08  + 0x500)

#define INT_STATUS_ACCESS_DENIED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x09  + 0x500)

#define INT_STATUS_UNEXPECTED_IO_ERROR \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0A + 0x500)

#define INT_STATUS_ACCESS_VIOLATION \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0B + 0x500)

#define INT_STATUS_ABANDONED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0C + 0x500)

#define INT_STATUS_OBJECT_TYPE_MISMATCH \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0D + 0x500)

#define INT_STATUS_INVALID_HANDLE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0E + 0x500)

#define INT_STATUS_NOT_READY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x0F + 0x500)

#define INT_STATUS_BUSY \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_COMMON, 0x10 + 0x500)

//
// informational statuses
//
#define INT_STATUS_NOT_NEEDED_HINT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_COMMON, 0x00)

#define INT_STATUS_NOT_INITIALIZED_HINT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_COMMON, 0x01)

#define INT_STATUS_ALREADY_INITIALIZED_HINT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_COMMON, 0x02)

#define INT_STATUS_REINITIALIZED_HINT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_COMMON, 0x03)

#define INT_STATUS_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_COMMON, 0x04)

//
// Generic error status. If possible, avoid using this.
///
#define INT_STATUS_UNSUCCESSFUL \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00FE)

/// Hook is under use.
#define INT_STATUS_HOOK_ACTIVE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0001)

/// Can be used by hook callbacks in order to signal that the hook should be removed.
#define INT_STATUS_REMOVE_HOOK_ON_RET \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0006)

/// Can be used by EPT violation callbacks to signal that the other callbacks that would normally be invoked for this
/// event must be skipped.
#define INT_STATUS_SKIP_OTHER_CALLBACKS \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0008)

/// Can be used by EPT violation callbacks to signal that the other callbacks that would normally be invoked for this
/// event must be skipped and that the hook should be removed.
#define INT_STATUS_REMOVE_AND_SKIP \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0009)

/// Can be used by detour callbacks to signal that the detour should be disabled.
#define INT_STATUS_DISABLE_DETOUR_ON_RET \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x000A)

/// Can be used to signal that a write is done only to a portion of the monitored structure and that processing
/// can be deferred until the entire structure is written.
#define INT_STATUS_PARTIAL_WRITE \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x000B)

/// Can be used by any callback that returns an #INTRO_ACTION in order to signal that the action should be taken
/// even if Introcore is in log-only mode.
///
/// This can be used to block events even if we normally would not block them
/// due to the current policy.
#define INT_STATUS_FORCE_ACTION_ON_BETA \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x000C)

/// Can be used by iteration callbacks to break the iteration early.
#define INT_STATUS_BREAK_ITERATION \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x000E)

/// Signals that no emulation is needed for this event.
#define INT_STATUS_NO_DETOUR_EMU \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x000F)

/// Raises an EPT event. Can be used to treat another event as an EPT violation.
#define INT_STATUS_RAISE_EPT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0010)

/// Indicates that an instruction was patched.
#define INT_STATUS_INSTRUCTION_PATCHED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x0011)

/// Indicates that an exception matched and the event must be allowed.
/// @ingroup group_exceptions
#define INT_STATUS_EXCEPTION_ALLOW \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x00E1)

/// Indicates that the current event is part of the process initialization phase and should be allowed.
/// @ingroup group_exceptions
#define INT_STATUS_EXCEPTION_CHECKS_OK \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x00E2)

/// Indicates that an exception signature matched.
/// @ingroup group_exceptions
#define INT_STATUS_SIGNATURE_MATCHED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x00E3)

/// No exception matched.
/// @ingroup group_exceptions
#define INT_STATUS_EXCEPTION_NOT_MATCHED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00E1)

/// The checks on the exception failed (a wrong value, a invalid pointer, etc).
/// @ingroup group_exceptions
#define INT_STATUS_EXCEPTION_CHECKS_FAILED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00E2)

/// No signature matched.
/// @ingroup group_exceptions
#define INT_STATUS_SIGNATURE_NOT_FOUND \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00E3)

/// Block the event and return to the guest. No more checks are to be done after this status.
/// @ingroup group_exceptions
#define INT_STATUS_EXCEPTION_BLOCK \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00EF)

/// Indicates that the detour should be completely removed and the guest RIP should be moved to the beginning of
/// the hooked function.
#define INT_STATUS_REMOVE_DETOUR_AND_SET_RIP \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_INFORMATIONAL, INT_FACILITY_HVI, 0x00E4)

/// Indicates that the guest crashed and Introcore must be deactivated.
#define INT_STATUS_UNINIT_BUGCHECK \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00E4)

/// Indicates that not all mapping structures of a virtual address are present.
#define INT_STATUS_NO_MAPPING_STRUCTURES \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0013)

/// Indicates that a virtual address is not present.
#define INT_STATUS_PAGE_NOT_PRESENT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0016)

/// Indicates a decoder error.
#define INT_STATUS_DISASM_ERROR \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0020)

/// Indicates that the guest operating system is not supported.
#define INT_STATUS_GUEST_OS_NOT_SUPPORTED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0030L)

/// Indicates that Introcore can not unload in a safely manner.
#define INT_STATUS_CANNOT_UNLOAD \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0040L)

/// Indicates that Introcore loading was aborted.
#define INT_STATUS_LOAD_ABORTED \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0050L)

/// Indicates that the current API call can not be completed because the guest is in a power state transition.
///
/// Certain operations can not safely be done while the guest is transitioning to another power state so we refuse
/// them.
#define INT_STATUS_POWER_STATE_BLOCK \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0060L)

/// Indicates that the stack was needed in order to match the exceptions, but it is swapped out.
#define INT_STATUS_STACK_SWAPPED_OUT \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x0061L)

/// An unrecoverable error was detected. Introcore must be unloaded.
#define INT_STATUS_FATAL_ERROR \
    INT_MAKE_STATUS(INT_STATUS_SEVERITY_ERROR, INT_FACILITY_HVI, 0x00FF)

#endif // _INTROSTATUS_H_
